services:
  predict_hr_sql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: predict-hr-sql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=sa
      - ENVIRONMENT=${ENVIRONMENT}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
